- hosts: localhost 
  tasks: 
   - local_action:
      module: azure
      subscription_id: 52682313-9683-468c-9c76-309ecc3eb348
      management_cert_path: /root/.ssh/ssh_key.pem
      name: spintest
      role_size: Small
      image: b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu_DAILY_BUILD-precise-12_04_3-LTS-amd64-server-20131205-en-us-30GB
      location: 'East US'
      user: ubuntu
      ssh_cert_path: /root/.ssh/ssh_key.pem
      storage_account: devopsuser
      wait: yes
