---
- hosts: "{{ host }}"
  gather_facts: false
  become: true

  tasks:
  - name: "Deploying for {{ inventory_hostname }} !!!"
    debug: "msg={{ inventory_hostname }}"
 
  - name: Copying war file into webapps to access 
    become_user: root
    become: true
    copy: src=/var/lib/jenkins/workspace/NewCreditCardApplication/CreditCardApp.war dest=/opt/apache-tomcat-7.0.59/webapps/ force=yes


  #- name: Restart webapps
  #  become_user: root
  #  become: yes
  #  service: name=tomcat state=restarted
