---

    - include: stopvms.yml macname={{item}}
      with_items:
      - vm-test001
      - vm-test002
     

    - include: terminatevms.yml macname={{item}}
      with_items:
      - vm-test001
      - vm-test002  
    #- include: ssh-key-share.yml
