---

    - include_vars: "{{ playbook_dir }}/roles/vmprovision/vars/main.yml" 

    - name: Sudoers update sudoers file and validate#
      lineinfile:
        dest: /etc/sudoers
        insertafter: EOF
        line: "{{ admin_user }} ALL=(ALL) NOPASSWD: ALL"
        state: present 
        create: yes
