---

# Ansible role to install jenkins

  # Include repo file
  - include: repo.redhat.yml

  - name: Install Jenkins
    yum: name=jenkins state=latest
    register: jenkins_install

  - name: Ensure jenkins is running
    service:
      name: jenkins
      state: started

  - name: Start jenkins on boot
    shell: chkconfig jenkins on

  # Configure jenkins
  - include: config.yml
 
