- hosts: provision 
  #remote_user: root
  connection: local
  tasks:
    - name: Stop Virtual Machine
      azure_rm_virtualmachine:
        resource_group: devops-resource-grp
        name: vm-test001
        ad_user: 
        password: 
        subscription_id: 
        started: no
        
